export const COURSES_MICROSERVICE = 'COURSES_MICROSERVICE';
export const coursesMessagePattern ={
    GET_ALL_COURSES: 'GET_ALL_COURSES',
    //GET_COURSE: 'GET_COURSE',
    CREATE_COURSE: 'CREATE_COURSE',
    UPDATE_COURSE: 'UPDATE_COURSE',
    //DELETE_COURSE: 'DELETE_COURSE',
}
export const CHANNEL_NOTIFICATION = 'send-email';